# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50e8f65c41cdbd61621f949743df28f79f0c6cdd1243ffd4230718721bf2d70186e9d295421c987b78d34e07dc153f56d72c5897e433443711392629082f75d4

test:
  secret_key_base: 1d2fcdbd75aa956a59d7cf65b039482ec51970ced279b4ea76118ad8f4845fc35ee093211b126837bcfb88b608998244ee4d68f20f6cf8d9bddd6402053fc1f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
